# Generated by Django 4.1.5 on 2023-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.DateField(verbose_name='Возраст'),
        ),
    ]
